; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"

; Features
projects[drupaleasy_slideshow][download][type] = "git"
projects[drupaleasy_slideshow][download][url] = "ultimike@git.drupal.org:sandbox/ultimike/1822938.git"
projects[drupaleasy_slideshow][type] = "module"
projects[drupaleasy_slideshow][subdir] = "features"

; Modules
projects[ctools][subdir] = "contrib"
projects[draggableviews][subdir] = "contrib"
projects[entity][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[field_redirection][subdir] = "contrib"
projects[flexslider][subdir] = "contrib"
projects[libraries][subdir] = "contrib"
projects[link][subdir] = "contrib"
projects[strongarm][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[views_slideshow][subdir] = "contrib"

; Themes
projects[omega][subdir] = "contrib"

; Libraries
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "https://github.com/woothemes/FlexSlider/zipball/master"
libraries[jquery.cycle][destination] = "libraries"
libraries[jquery.cycle][directory_name] = "flexslider"
libraries[jquery.cycle][type] = "library"

libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "https://raw.github.com/malsup/cycle/master/jquery.cycle.all.js"
libraries[jquery.cycle][destination] = "libraries"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

